name: float
version: "1.0.9"
license: "GPL-2.0-or-later"
date: 2025-08-26
description: |
    Integration of mpfr, mpfi, mpc, fplll and cxsc in GAP

authors:
    - name: Laurent Bartholdi
      url: https://www.math.uni-sb.de/ag/bartholdi/

maintainers:
    - name: Laurent Bartholdi
      url: https://www.math.uni-sb.de/ag/bartholdi/

GAP: ">=4.12.0"

needed-pkgs:
    - name: "GAPDoc"
      version: ">=1.0"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/float/
readme: README.md
packageinfo: https://gap-packages.github.io/float/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/float/releases/download/v1.0.9/float-1.0.9.tar.gz

abstract: |
    The <span class="pkgname">float</span> package allows                     GAP to manipulate floating-point numbers with arbitrary                     precision. It is based on MPFR, MPFI, MPC, CXSC, FPLLL

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    floating-point.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Bar25</span>]   <b class='BibAuthor'>Bartholdi, L.</b>,
     <i class='BibTitle'>float, Integration of mpfr, mpfi, mpc, fplll and cxsc in GAP,
             Version 1.0.9</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/float/">https://gap-packages.github.io/float/</a></span>.
    </p>
    

bibtex: |
    @misc{ float,
      author =           {Bartholdi, L.},
      title =            {{float},  {Integration  of  mpfr, mpfi, mpc, fplll and
                          cxsc in GAP}, {V}ersion 1.0.9},
      month =            {Aug},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href          {https://gap-packages.github.io/float/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{float/}}},
      keywords =         {floating-point},
      printedkey =       {Bar25}
    }

