name: float
version: 1.0.1
date: 2021-11-26
description: |
    Integration of mpfr, mpfi, mpc, fplll and cxsc in GAP

authors:
    - name: Laurent Bartholdi
      url: https://www.math.uni-sb.de/ag/bartholdi/

maintainers:
    - name: Laurent Bartholdi
      url: https://www.math.uni-sb.de/ag/bartholdi/

GAP: ">=4.11.0"

needed-pkgs:
    - name: "GAPDoc"
      version: ">=1.0"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/float/
readme: README.md
packageinfo: https://gap-packages.github.io/float/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/float/releases/download/v1.0.1/float-1.0.1.tar.gz

abstract: |
    The <span class="pkgname">float</span> package allows                     GAP to manipulate floating-point numbers with arbitrary                     precision. It is based on MPFR, MPFI, MPC, CXSC, FPLLL

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
